// <auto-generated />
using System;
using IBS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IBS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IbsDbContext))]
    [Migration("20260829080659_AddQuotationSharedAt")]
    partial class AddQuotationSharedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IBS.Modules.Sales.Domain.Entities.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AssignedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("AssignedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedToEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BudgetMax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BudgetMin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("ContactedDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FloorPlanBlobUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FloorPlanContentType")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FloorPlanFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long?>("FloorPlanSizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("FloorPlanUploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsInterested")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("NextFollowUpDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("OverallStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("Phase")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PropertyAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PropertyConfiguration")
                        .HasColumnType("int");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("PropertySize")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PropertySizeUnit")
                        .HasColumnType("int");

                    b.Property<int>("PropertyType")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("QuotationSharedAt")
                        .HasColumnType("date");

                    b.Property<string>("SecondaryPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdatedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToEmployeeId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("NextFollowUpDate");

                    b.HasIndex("OverallStatus");

                    b.HasIndex("Phase");

                    b.ToTable("Leads", (string)null);
                });

            modelBuilder.Entity("IBS.Modules.Sales.Domain.Entities.LeadRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("bit");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RoomKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdatedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.ToTable("LeadRooms", (string)null);
                });

            modelBuilder.Entity("IBS.Modules.Sales.Domain.Entities.LeadRoomRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("bit");

                    b.Property<string>("ItemKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("LeadRoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdatedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LeadRoomId");

                    b.ToTable("LeadRoomRequirements", (string)null);
                });

            modelBuilder.Entity("IBS.Modules.UsersAccess.Domain.Entities.ActivationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("InvalidatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Purpose")
                        .HasColumnType("int");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("EmployeeId", "Purpose");

                    b.ToTable("ActivationTokens", (string)null);
                });

            modelBuilder.Entity("IBS.Modules.UsersAccess.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ActorEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TargetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ActorEmployeeId");

                    b.HasIndex("TargetId");

                    b.HasIndex("Timestamp");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("IBS.Modules.UsersAccess.Domain.Entities.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdatedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Branches", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b7a10000-0000-4000-8000-000000000001"),
                            City = "Bengaluru",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Bengaluru",
                            Timezone = "Asia/Kolkata"
                        },
                        new
                        {
                            Id = new Guid("b7a10000-0000-4000-8000-000000000002"),
                            City = "Chennai",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Chennai",
                            Timezone = "Asia/Kolkata"
                        },
                        new
                        {
                            Id = new Guid("b7a10000-0000-4000-8000-000000000003"),
                            City = "Pune",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Pune",
                            Timezone = "Asia/Kolkata"
                        },
                        new
                        {
                            Id = new Guid("b7a10000-0000-4000-8000-000000000004"),
                            City = "Hyderabad",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Hyderabad",
                            Timezone = "Asia/Kolkata"
                        });
                });

            modelBuilder.Entity("IBS.Modules.UsersAccess.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateOnly>("FinancialYearStart")
                        .HasColumnType("date");

                    b.Property<string>("Gstin")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RegisteredAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdatedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Company", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0119a11-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Currency = "INR",
                            FinancialYearStart = new DateOnly(2026, 4, 1),
                            LegalName = "IBS"
                        });
                });

            modelBuilder.Entity("IBS.Modules.UsersAccess.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdatedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4e10000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Sales"
                        },
                        new
                        {
                            Id = new Guid("d4e10000-0000-4000-8000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Design"
                        },
                        new
                        {
                            Id = new Guid("d4e10000-0000-4000-8000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Estimation"
                        },
                        new
                        {
                            Id = new Guid("d4e10000-0000-4000-8000-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Procurement"
                        },
                        new
                        {
                            Id = new Guid("d4e10000-0000-4000-8000-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Execution"
                        },
                        new
                        {
                            Id = new Guid("d4e10000-0000-4000-8000-000000000006"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "Finance"
                        });
                });

            modelBuilder.Entity("IBS.Modules.UsersAccess.Domain.Entities.Designation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsSalesRole")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdatedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Designations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d5a10000-0000-4000-8000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSalesRole = false,
                            Name = "Super Admin"
                        },
                        new
                        {
                            Id = new Guid("d5a10000-0000-4000-8000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSalesRole = false,
                            Name = "Company Admin"
                        },
                        new
                        {
                            Id = new Guid("d5a10000-0000-4000-8000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSalesRole = false,
                            Name = "Business Head"
                        },
                        new
                        {
                            Id = new Guid("d5a10000-0000-4000-8000-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSalesRole = true,
                            Name = "Sales Manager"
                        },
                        new
                        {
                            Id = new Guid("d5a10000-0000-4000-8000-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSalesRole = true,
                            Name = "Sales Executive"
                        },
                        new
                        {
                            Id = new Guid("d5a10000-0000-4000-8000-000000000006"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSalesRole = true,
                            Name = "Pre-sales / Telecaller"
                        },
                        new
                        {
                            Id = new Guid("d5a10000-0000-4000-8000-000000000007"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSalesRole = false,
                            Name = "Design Head"
                        },
                        new
                        {
                            Id = new Guid("d5a10000-0000-4000-8000-000000000008"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSalesRole = false,
                            Name = "Interior Designer"
                        },
                        new
                        {
                            Id = new Guid("d5a10000-0000-4000-8000-000000000009"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSalesRole = false,
                            Name = "3D Visualiser"
                        },
                        new
                        {
                            Id = new Guid("d5a10000-0000-4000-8000-000000000010"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSalesRole = false,
                            Name = "Draftsman / CAD"
                        },
                        new
                        {
                            Id = new Guid("d5a10000-0000-4000-8000-000000000011"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSalesRole = false,
                            Name = "Estimator / QS"
                        },
                        new
                        {
                            Id = new Guid("d5a10000-0000-4000-8000-000000000012"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSalesRole = false,
                            Name = "Procurement Executive"
                        },
                        new
                        {
                            Id = new Guid("d5a10000-0000-4000-8000-000000000013"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSalesRole = false,
                            Name = "Store Keeper"
                        },
                        new
                        {
                            Id = new Guid("d5a10000-0000-4000-8000-000000000014"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSalesRole = false,
                            Name = "Project Manager"
                        },
                        new
                        {
                            Id = new Guid("d5a10000-0000-4000-8000-000000000015"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSalesRole = false,
                            Name = "Site Supervisor"
                        },
                        new
                        {
                            Id = new Guid("d5a10000-0000-4000-8000-000000000016"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSalesRole = false,
                            Name = "QC Inspector"
                        },
                        new
                        {
                            Id = new Guid("d5a10000-0000-4000-8000-000000000017"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSalesRole = false,
                            Name = "Accounts Executive"
                        },
                        new
                        {
                            Id = new Guid("d5a10000-0000-4000-8000-000000000018"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSalesRole = false,
                            Name = "HR Executive"
                        },
                        new
                        {
                            Id = new Guid("d5a10000-0000-4000-8000-000000000019"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsSalesRole = false,
                            Name = "Customer Support"
                        });
                });

            modelBuilder.Entity("IBS.Modules.UsersAccess.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateOfJoining")
                        .HasColumnType("date");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DesignationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("EmploymentType")
                        .HasColumnType("int");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("FirstFailedLoginAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LockoutEndsAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("ReportingManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdatedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("DesignationId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("IsSuperAdmin")
                        .IsUnique()
                        .HasDatabaseName("UX_Employees_SingleSuperAdmin")
                        .HasFilter("[IsSuperAdmin] = 1");

                    b.HasIndex("ReportingManagerId");

                    b.HasIndex("Status");

                    b.HasIndex("DepartmentId", "BranchId");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("IBS.Modules.UsersAccess.Domain.Entities.EmployeeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdatedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeDocuments", (string)null);
                });

            modelBuilder.Entity("IBS.Modules.UsersAccess.Domain.Entities.EmployeePermission", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("GrantedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EmployeeId", "PermissionId");

                    b.HasIndex("GrantedByEmployeeId");

                    b.HasIndex("PermissionId");

                    b.ToTable("EmployeePermissions", (string)null);
                });

            modelBuilder.Entity("IBS.Modules.UsersAccess.Domain.Entities.EmployeeProfessionalProfile", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("Certifications")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("Languages")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortfolioLink")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Qualification")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.PrimitiveCollection<string>("SoftwareSkills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialisation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("EmployeeId");

                    b.ToTable("EmployeeProfessionalProfiles", (string)null);
                });

            modelBuilder.Entity("IBS.Modules.UsersAccess.Domain.Entities.EmployeeStatutory", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aadhaar")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BankDetails")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("Ctc")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Esic")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Pan")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PfUan")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("EmployeeId");

                    b.ToTable("EmployeeStatutory", (string)null);
                });

            modelBuilder.Entity("IBS.Modules.UsersAccess.Domain.Entities.EmployeeTargets", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("IncentivePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("MaxDiscountBeforeEscalation")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("MonthlyTarget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.PrimitiveCollection<string>("Territories")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("EmployeeTargets", (string)null);
                });

            modelBuilder.Entity("IBS.Modules.UsersAccess.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UpdatedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9e5b0000-0000-4000-8000-000000000001"),
                            Code = "manage_users",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Add people, edit their details, and run invite, suspend, reinstate and deactivate actions.",
                            GroupName = "People & access",
                            Name = "Can manage users",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("9e5b0000-0000-4000-8000-000000000002"),
                            Code = "manage_permissions",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Grant or revoke the two high-impact permissions, and rename or regroup the catalogue.",
                            GroupName = "People & access",
                            Name = "Can manage permissions",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("9e5b0000-0000-4000-8000-000000000003"),
                            Code = "view_sensitive_data",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Read the statutory record: PAN, Aadhaar, bank details, PF, ESIC and CTC.",
                            GroupName = "People & access",
                            Name = "Can view employee sensitive data",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("9e5b0000-0000-4000-8000-000000000004"),
                            Code = "manage_customer_onboarding",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Create and progress customer onboarding records.",
                            GroupName = "Sales pipeline",
                            Name = "Can manage customer onboarding",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("9e5b0000-0000-4000-8000-000000000005"),
                            Code = "manage_quotations",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Prepare, revise and issue quotations.",
                            GroupName = "Sales pipeline",
                            Name = "Can manage quotations",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = new Guid("9e5b0000-0000-4000-8000-000000000020"),
                            Code = "manage_leads",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "View all leads, create, edit, delete and (re)assign them to any employee.",
                            GroupName = "Sales pipeline",
                            Name = "Can manage leads",
                            SortOrder = 20
                        },
                        new
                        {
                            Id = new Guid("9e5b0000-0000-4000-8000-000000000021"),
                            Code = "manage_own_leads",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "View and edit only the leads assigned to them. Cannot reassign or delete a lead.",
                            GroupName = "Sales pipeline",
                            Name = "Can manage own leads",
                            SortOrder = 21
                        },
                        new
                        {
                            Id = new Guid("9e5b0000-0000-4000-8000-000000000006"),
                            Code = "manage_designs",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Upload and revise design files and moodboards.",
                            GroupName = "Design & estimation",
                            Name = "Can manage designs",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = new Guid("9e5b0000-0000-4000-8000-000000000007"),
                            Code = "manage_boq",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Build and revise the bill of quantities and its costing.",
                            GroupName = "Design & estimation",
                            Name = "Can manage BOQ and estimation",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = new Guid("9e5b0000-0000-4000-8000-000000000008"),
                            Code = "manage_projects",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Create projects, set milestones and assign teams.",
                            GroupName = "Delivery & execution",
                            Name = "Can manage projects",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = new Guid("9e5b0000-0000-4000-8000-000000000009"),
                            Code = "manage_tasks",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Create, assign and close tasks.",
                            GroupName = "Delivery & execution",
                            Name = "Can manage tasks",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = new Guid("9e5b0000-0000-4000-8000-000000000010"),
                            Code = "manage_site_progress",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Record site updates, snags and daily progress.",
                            GroupName = "Delivery & execution",
                            Name = "Can manage site progress",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = new Guid("9e5b0000-0000-4000-8000-000000000011"),
                            Code = "manage_procurement",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Raise and approve purchase orders.",
                            GroupName = "Procurement, inventory & vendors",
                            Name = "Can manage procurement",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = new Guid("9e5b0000-0000-4000-8000-000000000012"),
                            Code = "manage_inventory",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Record stock movements and adjust inventory.",
                            GroupName = "Procurement, inventory & vendors",
                            Name = "Can manage inventory",
                            SortOrder = 12
                        },
                        new
                        {
                            Id = new Guid("9e5b0000-0000-4000-8000-000000000013"),
                            Code = "manage_vendors",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Add and edit vendors and their rate cards.",
                            GroupName = "Procurement, inventory & vendors",
                            Name = "Can manage vendors",
                            SortOrder = 13
                        },
                        new
                        {
                            Id = new Guid("9e5b0000-0000-4000-8000-000000000014"),
                            Code = "manage_invoices",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Raise invoices and record payments against them.",
                            GroupName = "Finance",
                            Name = "Can manage invoices and payments",
                            SortOrder = 14
                        },
                        new
                        {
                            Id = new Guid("9e5b0000-0000-4000-8000-000000000015"),
                            Code = "manage_portal",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Decide what is published to the client portal.",
                            GroupName = "Client portal",
                            Name = "Can manage client portal publishing",
                            SortOrder = 15
                        },
                        new
                        {
                            Id = new Guid("9e5b0000-0000-4000-8000-000000000016"),
                            Code = "view_reports",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Open the reporting dashboards.",
                            GroupName = "Reporting & oversight",
                            Name = "Can view reports",
                            SortOrder = 16
                        },
                        new
                        {
                            Id = new Guid("9e5b0000-0000-4000-8000-000000000017"),
                            Code = "export_data",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Download list and report data as files.",
                            GroupName = "Reporting & oversight",
                            Name = "Can export data",
                            SortOrder = 17
                        },
                        new
                        {
                            Id = new Guid("9e5b0000-0000-4000-8000-000000000018"),
                            Code = "manage_company_settings",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Edit the company profile, branches, departments and designations.",
                            GroupName = "Administration",
                            Name = "Can manage company settings",
                            SortOrder = 18
                        },
                        new
                        {
                            Id = new Guid("9e5b0000-0000-4000-8000-000000000019"),
                            Code = "view_audit_log",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Read the record of who did what, and when.",
                            GroupName = "Administration",
                            Name = "Can view audit log",
                            SortOrder = 19
                        });
                });

            modelBuilder.Entity("IBS.Modules.Sales.Domain.Entities.LeadRoom", b =>
                {
                    b.HasOne("IBS.Modules.Sales.Domain.Entities.Lead", "Lead")
                        .WithMany("Rooms")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("IBS.Modules.Sales.Domain.Entities.LeadRoomRequirement", b =>
                {
                    b.HasOne("IBS.Modules.Sales.Domain.Entities.LeadRoom", "Room")
                        .WithMany("Requirements")
                        .HasForeignKey("LeadRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("IBS.Modules.UsersAccess.Domain.Entities.ActivationToken", b =>
                {
                    b.HasOne("IBS.Modules.UsersAccess.Domain.Entities.Employee", "Employee")
                        .WithMany("ActivationTokens")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IBS.Modules.UsersAccess.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("IBS.Modules.UsersAccess.Domain.Entities.Employee", "ActorEmployee")
                        .WithMany()
                        .HasForeignKey("ActorEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActorEmployee");
                });

            modelBuilder.Entity("IBS.Modules.UsersAccess.Domain.Entities.Employee", b =>
                {
                    b.HasOne("IBS.Modules.UsersAccess.Domain.Entities.Branch", "Branch")
                        .WithMany("Employees")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IBS.Modules.UsersAccess.Domain.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IBS.Modules.UsersAccess.Domain.Entities.Designation", "Designation")
                        .WithMany("Employees")
                        .HasForeignKey("DesignationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IBS.Modules.UsersAccess.Domain.Entities.Employee", "ReportingManager")
                        .WithMany("DirectReports")
                        .HasForeignKey("ReportingManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");

                    b.Navigation("Department");

                    b.Navigation("Designation");

                    b.Navigation("ReportingManager");
                });

            modelBuilder.Entity("IBS.Modules.UsersAccess.Domain.Entities.EmployeeDocument", b =>
                {
                    b.HasOne("IBS.Modules.UsersAccess.Domain.Entities.Employee", "Employee")
                        .WithMany("Documents")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IBS.Modules.UsersAccess.Domain.Entities.EmployeePermission", b =>
                {
                    b.HasOne("IBS.Modules.UsersAccess.Domain.Entities.Employee", "Employee")
                        .WithMany("Permissions")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IBS.Modules.UsersAccess.Domain.Entities.Employee", "GrantedByEmployee")
                        .WithMany()
                        .HasForeignKey("GrantedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IBS.Modules.UsersAccess.Domain.Entities.Permission", "Permission")
                        .WithMany("EmployeePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("GrantedByEmployee");

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("IBS.Modules.UsersAccess.Domain.Entities.EmployeeProfessionalProfile", b =>
                {
                    b.HasOne("IBS.Modules.UsersAccess.Domain.Entities.Employee", "Employee")
                        .WithOne("ProfessionalProfile")
                        .HasForeignKey("IBS.Modules.UsersAccess.Domain.Entities.EmployeeProfessionalProfile", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IBS.Modules.UsersAccess.Domain.Entities.EmployeeStatutory", b =>
                {
                    b.HasOne("IBS.Modules.UsersAccess.Domain.Entities.Employee", "Employee")
                        .WithOne("Statutory")
                        .HasForeignKey("IBS.Modules.UsersAccess.Domain.Entities.EmployeeStatutory", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IBS.Modules.UsersAccess.Domain.Entities.EmployeeTargets", b =>
                {
                    b.HasOne("IBS.Modules.UsersAccess.Domain.Entities.Employee", "Employee")
                        .WithOne("Targets")
                        .HasForeignKey("IBS.Modules.UsersAccess.Domain.Entities.EmployeeTargets", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("IBS.Modules.Sales.Domain.Entities.Lead", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("IBS.Modules.Sales.Domain.Entities.LeadRoom", b =>
                {
                    b.Navigation("Requirements");
                });

            modelBuilder.Entity("IBS.Modules.UsersAccess.Domain.Entities.Branch", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("IBS.Modules.UsersAccess.Domain.Entities.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("IBS.Modules.UsersAccess.Domain.Entities.Designation", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("IBS.Modules.UsersAccess.Domain.Entities.Employee", b =>
                {
                    b.Navigation("ActivationTokens");

                    b.Navigation("DirectReports");

                    b.Navigation("Documents");

                    b.Navigation("Permissions");

                    b.Navigation("ProfessionalProfile");

                    b.Navigation("Statutory");

                    b.Navigation("Targets");
                });

            modelBuilder.Entity("IBS.Modules.UsersAccess.Domain.Entities.Permission", b =>
                {
                    b.Navigation("EmployeePermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
